### ISSUE TITLE
SketchUp Development Team

### ISSUE THREAD

**Issue by sketchup-extensions** [gpavlidi/rbs_unscrambler#1]
Dear Yanis Pavlidis,

We have taken notice of the rbs_unscrambler GitHub repository and how our SketchUp brand has been associated with it.

We appreciate your interest in our SketchUp product and our extension development program. However, I would like to request if you can please disassociate our SketchUp brand and our rbs file extension with your GitHub repository along with any reference to proprietary SketchUp Extension information.

(And, even though we know SketchUp is undeniably sexy, we do not like bragging about it.)

The success of the SketchUp extension ecosystem is based on a community that is self-reinforcing virtuous circle, with great plug-ins that provide extra value with our customers, and those customers supporting the extension developers.  With the mentioned repository you are enabling breaking this system and affecting our development community and the users we ultimately serve.

This is a courtesy notice, we have not involved our legal department just yet. We would like you to disassociate this GitHub repository with our brand and extension within two weeks of the timestamp on this GitHub notice. If you fail to comply with our request, we will be forced to use legal means to protect our brand.

Best Regards,

The SketchUp Development Team.

**Comment by gpavlidi** [comment]
See my reply https://github.com/gpavlidi/rbs_unscrambler/issues/2
